### ISSUE TITLE
xonsh envvars note

### ISSUE THREAD

**Issue by scopatz** [StyXman/ayrton#20]
Hey all, I am one of the xonsh developers, and I wanted to say that this is a very cool project.  I especially like the idea of a remote execution context manager. Definitely going to be putting that into xonsh :).

However, I did want to offer one point of clarification.  In the readme it says:

> xonsh keeps environment variables well separated from Python ones;

This is not strictly speaking true.  While we do make a syntactic distinction between internal-whitespace-insensitive "python-mode" and internal-whitespace-sensitive "subprocess-mode", the distinction isn't so clean.  We actually extend Python mode in a couple of ways through operators like `$` for environment lookup, `?` for help, `??` for super help, `$()` and `$[]` for subprocesses, and backtick regex strings.  These are all in python mode.  If an environment variable $VAR is a Python list, you can do things like `$VAR[::-1]` or any other valid list operation.

On the other hand, in subprocess-mode, aliases can be Python functions that are called with arguments that are passed in.  They never see an actual subprocess in such cases.

In essence, xonsh focuses on being a shell, as you say. But it tries to make it easy to migrate between these two modes.  If you could please modify the text of the readme to reflect this, I'd greatly appreciate it!

**Comment by StyXman** [comment]
What I meant with that is that they're too different namespaces, while `ayrton` keeps them in the same namespace. In fact, variables can be exported via `export()`, becoming envvars for subprocesses. I hope I didn't get `xonsh`'s semantic wrong; otherwise, I'll be happy to clarify/remove that reference.

**Comment by scopatz** [comment]
Hi @StyXman, yeah you are right that xonsh keeps the env namespace in a different dict from the python namespace.  If that is the point that you are trying to make, that's great, but I think the wording on the readme could be a little more clear.  What you said here is better.  I'd really appreciate the clarification. Thanks!
